blank_issues_enabled: false
contact_links:
  - name: Appimage package
    url: https://github.com/UnivaultOffice/appimage-desktopeditors/issues?q=
    about: Everything about the appimage version goes here.
  - name: Flatpak package
    url: https://github.com/flathub/org.univaultoffice.desktopeditors/issues?q=
    about: Everything about the flatpak version goes here.
  - name: Snap package
    url: https://github.com/UnivaultOffice/snap-desktopeditors/issues?q=
    about: Everything about the snap version goes here.
